### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by remjx** [NoniDOTio/LiveStreamRadio#1]
Your linked blog post no longer exists: https://noni.io/24-7-music-live-stream-raspberry-pi/

**Comment by NoniDOTio** [comment]
Hey there, thanks for letting me know. Will take some time until the blog is back up, but here's a very brief summary:
- install screen, alsa, git and mpg123
- install ffmpeg 4.1 or higher (you may have to compile it yourself or add a repository if the version in your default repositories is too old)
- run `modprobe snd-aloop pcm_substreams=1`
- run `nano /home/pi/.asoundrc` and add the line `pcm.!default { type plug slave.pcm "hw:Loopback,0,0" }`
- run `git clone https://github.com/NoniDOTio/LiveStreamRadio.git` to download LiveStreamRadio
- navigate to the LiveStreamRadio folder and edit `config.sh`
- run `./lsr.sh --help` to see a list of available commands
