### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by jbsix** [NoniDOTio/LiveStreamRadio#4]
Hi N-E great project. I'm running on ubuntu 20.04.4 and have everything working. Except there is no audio, even when using your sample mp3 file. Video is playing as expected and connecting to platforms as expected, however I'm seeing that the audio bit rate is less than 3kbp/s... the video is 3010 kb/s... any idea why there is no audio streaming?

**Comment by jbsix** [comment]
<img width="706" alt="Screen Shot 2022-10-24 at 3 55 53 PM" src="https://user-images.githubusercontent.com/9286189/197616581-f8b2820d-cb45-441a-b4e6-002f17eba44f.png">

**Comment by jbsix** [comment]
<img width="706" alt="Screen Shot 2022-10-24 at 3 55 53 PM" src="https://user-images.githubusercontent.com/9286189/197617251-2dc37cb2-c284-403f-b836-64c4b8e7454d.png">

**Comment by NoniDOTio** [comment]
Did you install alsa and follow these two steps from the README? You may have to run the first command with sudo.

- Add ALSA loopback (on some systems, you will have to re-run this command after every reboot)
```bash
modprobe snd-aloop pcm_substreams=1
```
- Add the following line to `~/.asoundrc`
```bash
pcm.!default { type plug slave.pcm "hw:Loopback,0,0" }
```
